[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
#	"-C", "link-arg=-fuse-ld=lld",
	"-C", "link-arg=--ld-path=wild",
	"-C", "split-debuginfo=unpacked",
	"-Z", "codegen-backend=cranelift",
	"-Z", "threads=8",
#	"--cfg", "tokio_unstable",
]

[build]
rustc-wrapper = "/usr/bin/sccache"
incremental = false

[profile.release]
strip = true
opt-level = 3
lto = false
panic = "abort"

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

